
# docker compose up -d
# version: '3'

services:
  db:
    container_name: mongo-container_name
    image: mongo:5.0.16
    volumes:
      - ./mongo:/data/db
    ports:
      - 27018:27017
    restart: always